app/urls.py
from django.urls import path, include

from . import views

urlpatterns = [

    path('', views.index, name="index"),
    path('api/chart-data/<str:chart>', views.chart_data_api),

    # Properties

    path('properties/', include([
        path('list', views.PropertyListView.as_view(), name="property_list"),
        path('detail/<int:pk>', views.PropertyEditView.as_view(),
             name="property_edit"),
        path('create/', views.PropertyCreateView.as_view(),
             name="property_create"),
        path('delete/<int:pk>', views.PropertyDeleteView.as_view(),
             name="property_delete"),
    ])),

    # Loans

    path('loans/', include([
        path('list/', views.LoanListView.as_view(), name="loan_list"),
        path('detail/<int:pk>', views.LoanEditView.as_view(), name="loan_edit"),
        path('create/', views.LoanCreateView.as_view(), name="loan_create"),
    ])),

    # Tenants

    path('tenants/', include([
         path('list', views.TenantListView.as_view(), name="tenant_list"),
         path('create/', views.TenantCreateView.as_view(), name="tenant_create"),
         path('detail/<int:pk>', views.TenantEditView.as_view(), name="tenant_edit"),
         path('detail/<int:pk>', views.TenantEditView.as_view(),
              name="tenant_edit_nested"),
         ])),

    # Expense table

    path('expense_table/', views.ExpenseTableView.as_view(), name="expense_table"),


]

form_generator/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from . import views

urlpatterns = [
    path('', views.FormListView.as_view(), name="form_generator"),
    path('form/', include([
        path('create/', views.FormCreateView, name="form_create"),
        path('fill/<uuid:pk>/', views.FormFillView.as_view(), name="form_fill"),
        path('edit/<uuid:pk>/', views.FormView.as_view(), name="form_edit"),
        path('delete/<uuid:pk>/', views.FormDeleteView.as_view(), name="form_delete"),
        path('thanks', views.ThanksView, name="thanks"),
        path('field/delete/<int:pk>/',
             views.FieldDeleteView.as_view(), name="field_delete")
    ])),
    path('submission/', include([
        path('detail/<int:pk>/', views.SubmissionDetailView.as_view(),
             name="submission_detail"),
        path('delete/<int:pk>/', views.SubmissionDeleteView.as_view(),
             name="submission_delete")
    ]))
]

real_estate_tool/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('landing/', include('landing.urls'))
]

if not settings.PRE_LAUNCH_MODE:
    urlpatterns += [
        path('accounts/', include('django.contrib.auth.urls')),
        path('register/', views.SignUpView.as_view(), name="register"),
        path('', include('app.urls')),
        path('form_generator/', include('form_generator.urls'))
    ]

form_generator/models.py
from django.urls import reverse

from django.contrib.auth.models import User
from django.db import models

from django import forms
from .forms import CustomForm
import uuid


class Form(models.Model):
    id = models.UUIDField(default=uuid.uuid4,
                          primary_key=True, editable=False, unique=True)
    name = models.CharField(max_length=30)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    @property
    def applicant_form(self):
        new_fields = {}
        for field in self.field_set.all():
            new_fields[field.question] = forms.CharField(max_length=60)
        form = type('form', (CustomForm,), new_fields)
        return form

    def get_absolute_url(self):
        return reverse("form_edit", kwargs={"pk": self.pk})

    def get_fill_url(self):
        return reverse("form_fill",  kwargs={"pk": self.pk})


class Field(models.Model):
    form = models.ForeignKey(Form, on_delete=models.CASCADE)
    question = models.CharField(max_length=40)
    # field_type = models.Charf


class Submission(models.Model):
    form = models.ForeignKey(Form, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    data = models.JSONField()

form_generator/forms.py
from django import forms


class FormCreate(forms.Form):
    name = forms.CharField(max_length=30, widget=forms.TextInput(
        attrs={'placeholder': 'Example: Tenant application form 1'}))


class CustomForm(forms.Form):
    pass

form_generator/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy

from django import forms
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.generic.edit import DeleteView, CreateView
from django.views.generic import View, ListView, DetailView

from django.forms import inlineformset_factory

from .models import Form, Field, Submission
from .forms import FormCreate, CustomForm

from django.http import HttpResponseForbidden


class FormListView(ListView):
    model = Form
    context_object_name = 'forms'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['form'] = FormCreate()
        context['submissions'] = Submission.objects.filter(
            form__user=self.request.user)
        return context


class FormDeleteView(DeleteView):
    model = Form
    success_url = reverse_lazy('form_generator')

    def get(self, *args, **kwargs):
        return super().post(*args, **kwargs)


class SubmissionDeleteView(DeleteView):
    model = Submission

    def get_success_url(self):
        return reverse_lazy('form_generator')

    def get(self, *args, **kwargs):
        return super().post(*args, **kwargs)


class SubmissionDetailView(DetailView):
    model = Submission
    template_name = 'form_generator/submission_detail.html'
    context_object_name = "submission"


class FieldDeleteView(DeleteView):
    model = Field

    def get_success_url(self):
        return self.get_object().form.get_absolute_url()

    def get(self, *args, **kwargs):
        return super().post(*args, **kwargs)


@login_required
def FormCreateView(request):
    if request.method == 'POST':
        form = FormCreate(request.POST)
        if form.is_valid():
            f = Form(user=request.user, name=form.cleaned_data.get('name'))
            f.save()
            messages.success(request, "Form has been created successfully")
            return redirect(f)
        else:
            messages.warning(request, "Form couldn't be created")
            return redirect('form_generator')


class FormView(View):
    FieldFormSet = inlineformset_factory(
        Form, Field, fields=('question',), extra=1, can_delete=False, widgets={
            'question': forms.TextInput(attrs={'class': 'form-control col-11'})
        })

    def get(self, request, pk=None):
        ctx = {
            'form': Form.objects.get(id=pk)
        }
        ctx['formset'] = self.FieldFormSet(instance=ctx['form'])
        return render(request, 'form_generator/form_create.html', ctx)

    def post(self, request, pk):
        instance = Form.objects.get(id=pk)
        form = self.FieldFormSet(request.POST, instance=instance)
        if form.is_valid():
            i = form.save()
        print(form.errors)
        return redirect(instance.get_absolute_url())


def ThanksView(request):
    return render(request, 'form_generator/thanks.html')


class FormFillView(View):

    def get(self, request, pk):
        form = Form.objects.get(pk=pk)
        if not request.user == form.user and f'filled_{pk}' not in request.session:
            return HttpResponseForbidden()
        return render(self.request, 'form_generator/form.html', {'form': form})

    def post(self, request, pk):
        f = Form.objects.get(pk=pk)

        if not request.user == f.user and f'filled_{pk}' not in request.session:
            return HttpResponseForbidden()

        form = f.applicant_form(request.POST)
        if form.is_valid():
            submission = Submission.objects.create(
                form=f, data=form.cleaned_data)
            request.session[f'filled_{pk}'] = True
            return redirect('thanks')

form_generator/templates/form_generator/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="shortcut icon"
      type="image/x-icon"
      href="{% static 'img/Logo-small.svg' %}"
    />
    <title>Realtool</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
  </head>
  <body>
    <div class="container-fluid full-h">
      <main role="main" class="">
        {% block content %} {% endblock content %}
      </main>
    </div>
  </body>
  <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"
  ></script>
  <script src='{% static "dynamic_formsets/jquery.formset.js" %}'></script>
  {% block script %} {% endblock script %}
</html>

form_generator/templates/form_generator/form.html
{% extends 'form_generator/base.html' %} {% load crispy_forms_tags %}
<!---->
{% block content %}
<div class="container mt-2">
  <form method="POST">
    {% csrf_token %} {{form.applicant_form|crispy}}
    <input type="submit" value="Submit" class="btn btn-primary" />
  </form>
</div>
{% endblock content %}

form_generator/templates/form_generator/form_create.html
{% extends 'app/base.html' %} {% load crispy_forms_tags %}{% block content %}<!---->

<div class="container mt-1 bg-white shadow-sm p-0">
  {% if messages %} {% for message in messages %}
  <div class="alert alert-{{ message.tags }}">{{message}}</div>
  {% endfor %} {% endif %}
  <h2 class="display-5 font-weight-normal card-header">{{form.name}}</h2>
  <div class="row p-4">
    <div class="col">
      <form action="" method="post" id="formset">
        <h4 class="font-weight-normal">Fields</h4>
        {% csrf_token %} {{ formset.management_form }}
        <!---->
        {% for field in formset %}
        <div class="row mx-1 mb-3">
          {{field}} {% if field.instance.id %}
          <a
            href="{% url 'field_delete' field.instance.id %}"
            class="col-1 btn btn-danger"
            >x</a
          ><!---->{% endif %}<!---->
        </div>
        {% endfor %}

        <input type="submit" value="Add" class="btn btn-primary" />
      </form>
    </div>
    <div class="col">
      <h4 class="font-weight-normal mb-3">Preview</h4>
      <div class="card p-3">
        {% for field in form.field_set.all %}
        <div class="form-group">
          <label>{{field.question}}</label>
          <input type="text" class="form-control" disabled />
          <!---->
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  <hr />
  <div class="d-flex justify-content-center pb-4">
    <div>
      <label for="copyText">Application URL:</label>
      <div class="input-group">
        <div class="input-group-prepend">
          <button
            class="btn btn-outline-secondary"
            onclick="copyText()"
            type="button"
          >
            Copy
          </button>
        </div>
        <input
          type="text"
          class="form-control"
          value="{{ request.scheme }}://{{ request.META.HTTP_HOST }}{{form.get_fill_url}}"
          placeholder=""
          aria-label=""
          aria-describedby="basic-addon1"
          id="copyText"
        />
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-center pb-3">
    <a
      class="btn btn-danger"
      onclick="return confirm('Are you sure you want to delete this form?')"
      href="{% url 'form_delete' form.id %}"
      >Delete form</a
    >
  </div>
</div>
{% endblock content %} {% block script %}
<script>
  const copyText = () => {
    let cp = $("#copyText");
    cp.select();
    //cp.setSelectionRange(0, 99999);
    document.execCommand("copy");
  };
  $(document).ready(() => {
    $("#formset form-group").formset({
      prefix: "{{ formset.prefix }}",
    });
  });
</script>
{% endblock script %}

form_generator/templates/form_generator/form_list.html
{% extends 'app/base.html' %} {% load crispy_forms_tags %} {% block content %}
<div class="container mt-1 bg-white shadow-sm p-0">
  <h2 class="display-5 font-weight-normal card-header">Form creator</h2>
  <div class="row p-4">
    <div class="col">
      <h4 class="font-weight-normal mb-3">Your forms</h4>
      {% for form in forms %}
      <div
        class="form-card card p-3 d-flex justify-content-between"
        onclick="location.href='{% url 'form_edit' form.id %}'"
      >
        <h3 class="d-inline">{{form.name}}</h3>
        <p>{{form.submission_set.count}} submissions</p>
      </div>
      {% empty %}
      <h5 class="font-weight-normal my-4 text-muted">
        You haven't created any forms yet...
      </h5>
      {% endfor %}
      <hr />
      <form action="{% url 'form_create' %}" class="mt-2 p-0" method="POST">
        <h4 class="font-weight-normal">Add a new form</h4>
        {% csrf_token %} {{form|crispy}}
        <input type="submit" value="Create" class="btn btn-primary" />
      </form>
    </div>
    <div class="col" data-spy="scroll">
      <h4 class="font-weight-normal mb-3">Submissions</h4>
      {% for submission in submissions %}
      <div
        class="card-sm form-card"
        onclick="location.href='{% url 'submission_detail' submission.id %}'"
      >
        <h5 class="card-header">
          {{submission.form.name}} <small>{{submission.created_at}}</small>
        </h5>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock content %}

form_generator/templates/form_generator/submission_detail.html
{% extends 'app/base.html' %} {% load crispy_forms_tags %}{% block content %}<!---->

<div class="container mt-1 bg-white shadow-sm p-0 pb-3">
  {% if messages %} {% for message in messages %}
  <div class="alert alert-{{ message.tags }}">{{message}}</div>
  {% endfor %} {% endif %}
  <h2 class="display-5 font-weight-normal card-header">
    {{submission.form.name}} submission details
    <p class="lead d-inline">Submitted at {{submission.created_at}}</p>
  </h2>
  <div class="card-body">
    {% for question, answer in submission.data.items %}
    <h5>Q: {{question}}</h5>
    <p>A: {{answer}}</p>
    {% endfor %}
  </div>
  <div class="d-flex justify-content-center">
    <a
      onclick="return confirm('Are you sure you want to delete this submission?')"
      href="{% url 'submission_delete' submission.id %}"
      class="btn btn-danger"
      >Delete</a
    >
  </div>
</div>
{% endblock content %}

form_generator/templates/form_generator/thanks.html
{% extends 'form_generator/base.html' %} {% block content %}
<h1 class="text-center mt-3">Thanks for submitting the application</h1>
{% endblock content %}